name: Feature/Hotfix CICD Template workflow

on:
  workflow_call:

jobs:
  feature_hotfix_workflow_template:
    runs-on: self-hosted
    environment: DEV
    env:
      ENV_NAME: ${{ startsWith(github.ref, 'refs/heads/feature/') && 'feature' || startsWith(github.ref, 'refs/heads/hotfix/') && 'hotfix' || 'other' }}
    steps:
      #1. Checkout Current Repository
      - name: Checkout Current Repository
        uses: actions/checkout@v4

      # 2. Checkout the shared-repo to get settings.xml
      - name: Checkout Shared-Runner-Templates Repository
        uses: actions/checkout@v4
        with:
          repository: narendar-gaddam_sfemu/shared-runner-templates
          path:  shared # Download shared-repo into this folder
          token: ${{ secrets.GH_SHARED_REPO_PAT }} # Required if shared-repo is private
          sparse-checkout: |
            mulesoft/maven
          sparse-checkout-cone-mode: false

      # 3. Build the package
      - name: BuildPackage
        run: mvn -B -U clean package -DskipASTValidation -DskipTests -s shared/mulesoft/maven/settings.xml 
        env:          
          CONNECTED_APP_ID: ${{ secrets.CONNECTED_APP_ID }}
          CONNECTED_APP_SECRET: ${{ secrets.CONNECTED_APP_SECRET }}
